package session

import (
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/pengjunchen/go-cli/internal/verify"
)

func TestQueueTypeString(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	assert.Equal(t, "steering", QueueSteering.String())
	assert.Equal(t, "follow_up", QueueFollowUp.String())
	assert.Equal(t, "next_run", QueueNextRun.String())
}

func TestSubmissionQueue_EnqueueDequeueFIFO(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()

	require.NoError(t, q.Enqueue(QueueSteering, QueuedSubmission{ID: "s1", Content: "first"}))
	require.NoError(t, q.Enqueue(QueueSteering, QueuedSubmission{ID: "s2", Content: "second"}))
	require.NoError(t, q.Enqueue(QueueSteering, QueuedSubmission{ID: "s3", Content: "third"}))

	assert.Equal(t, 3, q.Len(QueueSteering))

	item, ok := q.Dequeue(QueueSteering)
	require.True(t, ok)
	assert.Equal(t, "s1", item.ID)

	item, ok = q.Dequeue(QueueSteering)
	require.True(t, ok)
	assert.Equal(t, "s2", item.ID)

	item, ok = q.Dequeue(QueueSteering)
	require.True(t, ok)
	assert.Equal(t, "s3", item.ID)

	_, ok = q.Dequeue(QueueSteering)
	require.False(t, ok, "queue should be empty")
}

func TestSubmissionQueue_PeekDoesNotRemove(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	require.NoError(t, q.Enqueue(QueueFollowUp, QueuedSubmission{ID: "f1", Content: "peek-me"}))

	item, ok := q.Peek(QueueFollowUp)
	require.True(t, ok)
	assert.Equal(t, "f1", item.ID)
	assert.Equal(t, 1, q.Len(QueueFollowUp), "Peek must not remove the item")

	// Dequeue should return the same item.
	item, ok = q.Dequeue(QueueFollowUp)
	require.True(t, ok)
	assert.Equal(t, "f1", item.ID)
	assert.Equal(t, 0, q.Len(QueueFollowUp))
}

func TestSubmissionQueue_PeekEmpty(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	_, ok := q.Peek(QueueNextRun)
	require.False(t, ok)
}

func TestSubmissionQueue_Drain(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	require.NoError(t, q.Enqueue(QueueNextRun, QueuedSubmission{ID: "n1", Content: "a"}))
	require.NoError(t, q.Enqueue(QueueNextRun, QueuedSubmission{ID: "n2", Content: "b"}))
	require.NoError(t, q.Enqueue(QueueNextRun, QueuedSubmission{ID: "n3", Content: "c"}))

	items := q.Drain(QueueNextRun)
	require.Len(t, items, 3)
	assert.Equal(t, "n1", items[0].ID)
	assert.Equal(t, "n2", items[1].ID)
	assert.Equal(t, "n3", items[2].ID)
	assert.Equal(t, 0, q.Len(QueueNextRun), "queue must be empty after drain")
}

func TestSubmissionQueue_DrainEmpty(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	items := q.Drain(QueueSteering)
	assert.Empty(t, items)
}

func TestSubmissionQueue_Abort(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	require.NoError(t, q.Enqueue(QueueFollowUp, QueuedSubmission{ID: "f1", Content: "a"}))
	require.NoError(t, q.Enqueue(QueueFollowUp, QueuedSubmission{ID: "f2", Content: "b"}))

	count := q.Abort(QueueFollowUp)
	assert.Equal(t, 2, count)
	assert.Equal(t, 0, q.Len(QueueFollowUp))

	// Abort on empty queue returns 0.
	count = q.Abort(QueueFollowUp)
	assert.Equal(t, 0, count)
}

func TestSubmissionQueue_IndependentQueues(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	require.NoError(t, q.Enqueue(QueueSteering, QueuedSubmission{ID: "s1", Content: "steer"}))
	require.NoError(t, q.Enqueue(QueueFollowUp, QueuedSubmission{ID: "f1", Content: "follow"}))
	require.NoError(t, q.Enqueue(QueueNextRun, QueuedSubmission{ID: "n1", Content: "next"}))

	assert.Equal(t, 1, q.Len(QueueSteering))
	assert.Equal(t, 1, q.Len(QueueFollowUp))
	assert.Equal(t, 1, q.Len(QueueNextRun))
	assert.Equal(t, 3, q.TotalLen())

	item, ok := q.Dequeue(QueueSteering)
	require.True(t, ok)
	assert.Equal(t, "s1", item.ID)
	assert.Equal(t, 1, q.Len(QueueFollowUp), "follow-up queue must be unaffected")
}

func TestSubmissionQueue_AutoGeneratedID(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	require.NoError(t, q.Enqueue(QueueSteering, QueuedSubmission{Content: "no id"}))

	item, ok := q.Dequeue(QueueSteering)
	require.True(t, ok)
	assert.NotEmpty(t, item.ID, "an auto-generated id should be assigned")
}

func TestSubmissionQueue_EnqueueAtTimestamp(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	require.NoError(t, q.Enqueue(QueueSteering, QueuedSubmission{ID: "s1", Content: "ts"}))

	item, ok := q.Dequeue(QueueSteering)
	require.True(t, ok)
	assert.False(t, item.EnqueuedAt.IsZero(), "EnqueuedAt should be set when zero")
}

func TestSubmissionQueue_InvalidQueueType(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	err := q.Enqueue(QueueType(99), QueuedSubmission{ID: "x"})
	require.Error(t, err)

	_, ok := q.Dequeue(QueueType(99))
	require.False(t, ok)

	_, ok = q.Peek(QueueType(99))
	require.False(t, ok)

	assert.Equal(t, 0, q.Len(QueueType(99)))
	assert.Nil(t, q.Drain(QueueType(99)))
	assert.Equal(t, 0, q.Abort(QueueType(99)))
}

func TestSubmissionQueue_Mode(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	assert.Equal(t, QueueModeOneAtATime, q.Mode())

	q.SetMode(QueueModeAll)
	assert.Equal(t, QueueModeAll, q.Mode())

	q2 := NewDefaultSubmissionQueueWithMode(QueueModeAll)
	assert.Equal(t, QueueModeAll, q2.Mode())
}

func TestSubmissionQueue_Concurrent(t *testing.T) {
	defer verify.AssertNoGoroutineLeak(t)()

	q := NewDefaultSubmissionQueue()
	const n = 50

	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func(i int) {
			defer wg.Done()
			require.NoError(t, q.Enqueue(QueueSteering, QueuedSubmission{
				ID:      "s" + itoa(i),
				Content: "content",
			}))
		}(i)
	}
	wg.Wait()

	assert.Equal(t, n, q.Len(QueueSteering))

	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			_, ok := q.Dequeue(QueueSteering)
			require.True(t, ok)
		}()
	}
	wg.Wait()

	assert.Equal(t, 0, q.Len(QueueSteering))
}

// itoa is a minimal int-to-string helper to avoid importing strconv.
func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	var buf [20]byte
	pos := len(buf)
	neg := i < 0
	if neg {
		i = -i
	}
	for i > 0 {
		pos--
		buf[pos] = byte('0' + i%10)
		i /= 10
	}
	if neg {
		pos--
		buf[pos] = '-'
	}
	return string(buf[pos:])
}
